TOXIC_SYNONYMS = {
    # --- Profanidades Comuns e Flexões ---
    "ass": "butt", 
    "asses": "butts", 
    "asshole": "jerk", 
    "assholes": "jerks", 
    "asshat": "fool", 
    "asshats": "fools", 
    "asswipe": "jerk", 
    "asswipes": "jerks", 
    "bastard": "scoundrel", 
    "bastards": "scoundrels", 
    "bitch": "jerk", 
    "bitches": "jerks", 
    "bitching": "complaining", 
    "bitched": "complained", 
    "bullshit": "nonsense", 
    "bullshitting": "joking", 
    "crap": "crud", 
    "craps": "cruds", 
    "crappy": "lousy", 
    "crapping": "pooping", 
    "damn": "darn", 
    "damnit": "darnit", 
    "damned": "darned", 
    "damning": "condemning", 
    "dick": "jerk", 
    "dicks": "jerks", 
    "dickhead": "idiot", 
    "dickheads": "idiots", 
    "dipshit": "fool", 
    "dipshits": "fools", 
    "douche": "jerk", 
    "douches": "jerks", 
    "douchebag": "jerk", 
    "douchebags": "jerks", 
    "fuck": "screw", 
    "fucks": "screws", 
    "fucker": "jerk", 
    "fuckers": "jerks", 
    "fucking": "freaking", 
    "fucked": "messed up", 
    "fuckface": "idiot", 
    "fuckhead": "idiot", 
    "fucktard": "idiot", 
    "fucktards": "idiots", 
    "motherfucker": "scumbag", 
    "motherfuckers": "scumbags", 
    "motherfucking": "freaking", 
    "shit": "crud", 
    "shits": "cruds", 
    "shitting": "pooping", 
    "shitted": "pooped", 
    "shitface": "fool", 
    "shithead": "fool", 
    "shitty": "lousy",
    
    # --- Ofensas Compostas ---
    "clusterfuck": "disaster", 
    "dumbass": "fool", 
    "dumbasses": "fools", 
    "dumbfuck": "idiot", 
    "dumbfucks": "idiots", 
    "fatass": "heavy", 
    "fatasses": "heavies", 
    "jackass": "fool", 
    "jackasses": "fools", 
    "circlejerk": "echo chamber", 
    "fudgepacker": "gay", 
    "gangbang": "group activity", 
    "gangbanged": "jumped", 
    "jackoff": "goof off", 
    "jerkoff": "idiot", 
    "jizz": "spit", 
    "jizzing": "spitting", 
    "jizzed": "spit", 
    "pecker": "bird", 
    "peckers": "birds", 
    "piss": "pee", 
    "pisses": "pees", 
    "pissed": "mad", 
    "pissing": "peeing", 
    "sonofabitch": "scoundrel",

    # --- Insultos Severos e Slurs ---
    "beaner": "hispanic", 
    "beaners": "hispanics", 
    "chink": "asian", 
    "chinks": "asians", 
    "coon": "black", 
    "coons": "blacks", 
    "cracker": "white", 
    "crackers": "whites", 
    "cunt": "coward", 
    "cunts": "cowards", 
    "dago": "italian", 
    "dagos": "italians", 
    "dyke": "lesbian", 
    "dykes": "lesbians", 
    "fag": "gay", 
    "fags": "gays", 
    "faggot": "gay", 
    "faggots": "gays", 
    "gook": "asian", 
    "gooks": "asians", 
    "honkey": "white", 
    "honkeys": "whites", 
    "jigaboo": "black", 
    "kike": "jewish", 
    "kikes": "jewish", 
    "nazi": "fascist", 
    "nazis": "fascists", 
    "nigga": "dude", 
    "niggas": "dudes", 
    "nigger": "black", 
    "niggers": "blacks", 
    "paki": "pakistani", 
    "pakis": "pakistanis", 
    "raghead": "arab", 
    "ragheads": "arabs", 
    "retard": "fool", 
    "retards": "fools", 
    "retarded": "foolish", 
    "sandnigger": "arab", 
    "shemale": "transgender", 
    "shemales": "transgender", 
    "slanteye": "asian", 
    "spic": "hispanic", 
    "spics": "hispanics", 
    "towelhead": "arab", 
    "tranny": "transgender", 
    "trannies": "transgender", 
    "twat": "jerk", 
    "twats": "jerks", 
    "wetback": "hispanic", 
    "wetbacks": "hispanics", 
    "wigger": "poser", 
    "wiggers": "posers",
    "pajeet": "indian",
    "poopjeet": "indian",
    "pajeets": "indians",
    "poopjeets": "indians",
    # --- Termos Sexuais Explícitos ---
    "anal": "back", 
    "anilingus": "kissing", 
    "blowjob": "favor", 
    "blowjobs": "favors", 
    "boob": "chest", 
    "boobs": "chest", 
    "bukkake": "mess", 
    "clit": "button", 
    "clits": "buttons", 
    "clitoris": "anatomy", 
    "cock": "unit", 
    "cocks": "units", 
    "cocksucker": "bootlicker", 
    "cocksuckers": "bootlickers", 
    "creampie": "mess", 
    "creampies": "messes", 
    "cum": "fluid", 
    "cums": "fluids", 
    "cumming": "arriving", 
    "cummed": "arrived", 
    "cumshot": "picture", 
    "cumshots": "pictures", 
    "cunnilingus": "kissing", 
    "dildo": "toy", 
    "dildos": "toys", 
    "ejaculate": "release", 
    "ejaculated": "released", 
    "ejaculating": "releasing", 
    "ejaculation": "release", 
    "fellatio": "favor", 
    "fingering": "touching", 
    "fisting": "hitting", 
    "gloryhole": "hole", 
    "handjob": "massage", 
    "handjobs": "massages", 
    "masturbate": "touch", 
    "masturbated": "touched", 
    "masturbating": "touching", 
    "masturbation": "touching", 
    "orgasm": "climax", 
    "orgasms": "climaxes", 
    "penis": "anatomy", 
    "penises": "anatomy", 
    "porn": "adult media", 
    "porno": "adult media", 
    "pornos": "adult media", 
    "pornography": "adult media", 
    "pussy": "coward", 
    "pussies": "cowards", 
    "scat": "mess", 
    "schlong": "anatomy", 
    "semen": "fluid", 
    "smut": "dirt", 
    "sodomy": "intercourse", 
    "sperm": "seed", 
    "tits": "chest", 
    "titties": "chest", 
    "vagina": "anatomy", 
    "vaginas": "anatomy", 
    "vulva": "anatomy", 
    "vulvas": "anatomy", 
    "wank": "mess around", 
    "wanker": "fool", 
    "wankers": "fools", 
    "wanking": "messing around",

    # --- Termos Derrogatórios (Gênero/Comportamento) ---
    "bimbo": "airhead", 
    "bimbos": "airheads", 
    "hooker": "escort", 
    "hookers": "escorts", 
    "milf": "mom", 
    "milfs": "moms", 
    "nympho": "maniac", 
    "nymphos": "maniacs", 
    "prostitute": "escort", 
    "prostitutes": "escorts", 
    "skank": "trash", 
    "skanks": "trash", 
    "slut": "flirt", 
    "sluts": "flirts", 
    "slutty": "flirty", 
    "tramp": "wanderer", 
    "tramps": "wanderers", 
    "whore": "escort", 
    "whores": "escorts", 
    "whoring": "selling out",

    # --- Anatomia Vulgar ---
    "anus": "bottom", 
    "ballsack": "sack", 
    "bollocks": "nonsense", 
    "butthole": "bottom", 
    "buttholes": "bottoms", 
    "cameltoe": "wedgie", 
    "crotch": "lap", 
    "crotches": "laps", 
    "prick": "jerk", 
    "pricks": "jerks", 
    "rectum": "bottom", 
    "scrotum": "anatomy", 
    "testicle": "anatomy", 
    "testicles": "anatomy", 
    "turd": "poop", 
    "turds": "poops",
    
    # --- Violência Sexual e Abuso ---
    "rape": "assault",
    "raped": "assaulted",
    "raping": "attacking",
    "rapist": "attacker",
    "rapists": "attackers",
    "pedophile": "predator",
    "pedophiles": "predators",
    "pedo": "predator",
    "pedos": "predators",
    "molest": "bother",
    "molested": "bothered",
    "molesting": "bothering",
    "molester": "abuser",
    "molesters": "abusers",
    "incest": "taboo",
    "bestiality": "taboo",
    
    # --- Conteúdo Adulto e Nudez ---
    "nude": "bare",
    "nudes": "pictures",
    "nudity": "bareness",
    "hentai": "anime",
    "bdsm": "roleplay",
    "fetish": "interest",
    "fetishes": "interests",
    "orgy": "party",
    "orgies": "parties",
    
    # --- Slurs Adicionais e Gírias ---
    "homo": "gay",
    "homos": "gays",
    "lesbo": "lesbian",
    "lesbos": "lesbians",
    "midget": "short",
    "midgets": "short",
    "shag": "sleep",
    "shags": "sleeps",
    "shagged": "slept",
    "shagging": "sleeping",
    
    # --- Automutilação ---
    "suicide": "tragedy",
    "suicidal": "reckless"
}